version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.4-browsers

    working_directory: ~/dreamshare

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test:
    docker:
      - image: circleci/node:8.11.4-browsers

    working_directory: ~/dreamshare

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn test
  lint:
    docker:
      - image: circleci/node:8.11.4-browsers

    working_directory: ~/dreamshare

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn lint

  # Deploying
  deploy-prod:
    docker:
      - image: circleci/node:8.11.4-browsers
    working_directory: ~/dreamshare

    steps:
      - checkout

      - command: # shell


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master

      - test:
          requires:
            - build

      - deploy-prod:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
