version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.4-browsers

    working_directory: ~/dreamshare

    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

  test:
    docker:
      - image: circleci/node:8.11.4-browsers

    working_directory: ~/dreamshare

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn run test:coverage
  lint:
    docker:
      - image: circleci/node:8.11.4-browsers

    working_directory: ~/dreamshare

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn lint

  # Deploying
  deploy-prod:
    docker:
      - image: circleci/node:8.11.4-browsers
    working_directory: ~/dreamshare

    steps:
      - checkout

      - command: # shell


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master

      - test:
          requires:
            - build

      - deploy-prod:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
